// Mocks generated by Mockito 5.4.0 from annotations
// in app_section_27/test/contact_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:app_section_27/model/contacts_model.dart' as _i6;
import 'package:app_section_27/utils/state/finit_state.dart' as _i5;
import 'package:app_section_27/view/screen/prioritas_2/prioritas_2_view_model.dart'
    as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Prioritas2ViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrioritas2ViewModel extends _i1.Mock
    implements _i4.Prioritas2ViewModel {
  MockPrioritas2ViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MyState get myState => (super.noSuchMethod(
        Invocation.getter(#myState),
        returnValue: _i5.MyState.initial,
      ) as _i5.MyState);
  @override
  set myState(_i5.MyState? _myState) => super.noSuchMethod(
        Invocation.setter(
          #myState,
          _myState,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);
  @override
  set database(_i2.Database? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.TextEditingController get nameController => (super.noSuchMethod(
        Invocation.getter(#nameController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#nameController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get phoneController => (super.noSuchMethod(
        Invocation.getter(#phoneController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#phoneController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get dateController => (super.noSuchMethod(
        Invocation.getter(#dateController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#dateController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get colorController => (super.noSuchMethod(
        Invocation.getter(#colorController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#colorController),
        ),
      ) as _i3.TextEditingController);
  @override
  _i3.TextEditingController get fileController => (super.noSuchMethod(
        Invocation.getter(#fileController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#fileController),
        ),
      ) as _i3.TextEditingController);
  @override
  List<_i6.ContacsModel> get contacts => (super.noSuchMethod(
        Invocation.getter(#contacts),
        returnValue: <_i6.ContacsModel>[],
      ) as List<_i6.ContacsModel>);
  @override
  set contacts(List<_i6.ContacsModel>? _contacts) => super.noSuchMethod(
        Invocation.setter(
          #contacts,
          _contacts,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);
  @override
  _i7.Future<void> initDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initDatabase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<dynamic> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<dynamic> addContact({
    required String? name,
    required String? nomor,
    required String? date,
    required String? color,
    required String? file,
    _i3.BuildContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContact,
          [],
          {
            #name: name,
            #nomor: nomor,
            #date: date,
            #color: color,
            #file: file,
            #context: context,
          },
        ),
        returnValue: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);
  @override
  _i7.Future<void> removeContact({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #removeContact,
          [],
          {#id: id},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  _i7.Future<void> updateContact({
    required int? id,
    required String? name,
    required String? nomor,
    required String? date,
    required String? color,
    required String? file,
    required _i3.BuildContext? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContact,
          [],
          {
            #id: id,
            #name: name,
            #nomor: nomor,
            #date: date,
            #color: color,
            #file: file,
            #context: context,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
